### ISSUE TITLE
Sourcing pcds_conda is causing designer's pcdswidgets to not load.

### ISSUE THREAD

**Issue by slacAdpai** [pcdshub/Bug-Reports-and-Requests#74] opened 2021-03-02 23:21 UTC
**Bug Report**

Sourcing pcds_conda is causing designer's pcdswidgets to not load. The PCDS devices are not loading properly and this error pops up.
![image](https://user-images.githubusercontent.com/42284230/109727903-0c6aae80-7b6a-11eb-8e6f-124cdf78c8ea.png)

**Expected Behavior**

Sourcing pcds_conda would not have any errors when loading up a screen. PCDS devices are loaded on the TMO Lamp vacuum screen.

**Context**

I noticed that source dev_conda worked much better and pcdsdevice widgets load.

**Steps To Reproduce**

1. >>ssh tmo-control
2. >>cd /cds/group/pcds/epics-dev/screens/pydm/vacuumscreens/screens/TMO
3. >>source pcds_conda
4.>>designer cvmiVac.ui

**Your Environment**

Sourcing pcds_conda has the errors. Sourcing dev_conda does not have these errors.

**Comment by ZLLentz** [comment] 2021-03-03 17:01
Closing as a duplicate of https://github.com/pcdshub/pcds-envs/issues/172

**Closed by ZLLentz** 2021-03-03 17:01 UTC
Labels: bug
